"""empty message

Revision ID: 03142a531ec1
Revises: b10f0ac18a45
Create Date: 2018-04-25 09:38:19.313206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03142a531ec1'
down_revision = 'b10f0ac18a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('coupons', sa.Column('description_changed', sa.Boolean(), nullable=True))
    op.add_column('coupons', sa.Column('title_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'title_changed')
    op.drop_column('coupons', 'description_changed')
    op.drop_column('coupons', 'code')
    # ### end Alembic commands ###
