"""empty message

Revision ID: 5b9ed173b678
Revises: ea38f92abf28
Create Date: 2018-04-10 10:36:26.000958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9ed173b678'
down_revision = 'ea38f92abf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('job_uid', sa.String(length=60), nullable=True))
    op.add_column('stores', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'status')
    op.drop_column('stores', 'job_uid')
    # ### end Alembic commands ###
