"""empty message

Revision ID: 6525b4aac66c
Revises: 5b9ed173b678
Create Date: 2018-04-11 19:02:05.262602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6525b4aac66c'
down_revision = '5b9ed173b678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
