"""empty message

Revision ID: b10f0ac18a45
Revises: 0770e1a3baea
Create Date: 2018-04-13 23:01:08.625340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10f0ac18a45'
down_revision = '0770e1a3baea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'status')
    # ### end Alembic commands ###
