"""empty message

Revision ID: b90c285c7a1a
Revises: 03142a531ec1
Create Date: 2018-04-26 07:19:21.869344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90c285c7a1a'
down_revision = '03142a531ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('original_description', sa.Text(), nullable=True))
    op.add_column('coupons', sa.Column('original_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'original_title')
    op.drop_column('coupons', 'original_description')
    # ### end Alembic commands ###
